### ISSUE TITLE
Wondering if you can help debugging with WebStorm?

### ISSUE THREAD

**Issue by born2net** [ocombe/ng2-webpack#10]
Wondering if you can help debugging with WebStorm?
As per WebStorm they require that we debug against a dist directory as specified in: https://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/

however, as per your scripts, when running webpack-dev-server, it is all in memory as in:
```
"server": "webpack-dev-server --inline --progress --colors --display-error-details --display-cached --hot --port=3000",
```

is it possible to run webpack-dev-server in a dist directory so we can have source maps so we can insert into WebStorm mapping for debugging?

tx

Sean

**Comment by ocombe** [comment]
Yes it's possible, you should use the `npm run watch` command, it will output files in the `dist` folder and you have to use your own local server (like [live-server](https://github.com/tapio/live-server) for example)

**Comment by born2net** [comment]
tx will give it a shot!
