### ISSUE TITLE
can you recommend best way to load bootstrap.css?

### ISSUE THREAD

**Issue by born2net** [ocombe/ng2-webpack#12]
can you recommend best way to load bootstrap.css?
of course it's css and not scss and I believe all css loading is disabled in your examples...

tx for the time

Sean

**Comment by yfilali** [comment]
I don't know if it's the best way, but I would start by having the scss version of bootstrap in src/style/ then add the import to app.scss:

```
@import "bootstrap-sprockets";
@import "bootstrap";
```

You can further customize bootstrap from there the usual sass way, updating variables, selecting individual modules etc.

**Comment by born2net** [comment]
tx ended up using http://blog.theodybrothers.com/2015/07/how-to-use-bootstrap-css-only-and.html

**Comment by ocombe** [comment]
You can require the css in any of the source files, in your case it would probably be vendor.ts:
`require('../../node_modules/bootstrap/dist/bootstrap.css')` (I don't know the real path, I'm making it up for the example).

**Comment by ocombe** [comment]
I just pushed a fix that should help and [updated the readme](https://github.com/ocombe/ng2-webpack#how-to-include-external-css-files-such-as-bootstrapcss-) accordingly
