### ISSUE TITLE
How to use bootstrap.css in entire app with webpack?

### ISSUE THREAD

**Issue by ibufu** [ocombe/ng2-webpack#14]

**Comment by ocombe** [comment]
This has been answered here: https://github.com/ocombe/ng2-webpack/issues/12

**Comment by ocombe** [comment]
Also, I just pushed a fix that should help and [updated the readme](https://github.com/ocombe/ng2-webpack#how-to-include-external-css-files-such-as-bootstrapcss-) accordingly

**Comment by ibufu** [comment]
sorry,  I add import '../node_modules/bootstrap/dist/css/bootstrap.css'; to vendor.ts
but it does not work.
I have to add <link href="../node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet"> to index.html.

**Comment by ibufu** [comment]
I can find bootstrap.css at webpack://~/bootstrap/dist/css. But how to use it to my components?

**Comment by ocombe** [comment]
To import it from vendor.ts you have to make this change to the webpack config file: https://github.com/ocombe/ng2-webpack/commit/f73e6e5161fbc94aa1d7497ca504071bcedea363#diff-11e9f7f953edc64ba14b0cc350ae7b9dR114

Then just do:
```ts
import 'bootstrap/dist/css/bootstrap.css';
```

It will import it for the whole project.
