### ISSUE TITLE
Getting Error during evaluation of "click" on production build

### ISSUE THREAD

**Issue by Enlitened** [ocombe/ng2-webpack#16]
When trying to run the site from the /dist folder after doing an "npm run build", I get the following exception in chrome dev tools console: 

`Error during evaluation of "click"`, 

```
TypeError: this.directive_1_0.onClick is not a function
    at t.ChangeDetector_e_0.handleEventInternal (viewFactory_e:275)
    at t.handleEvent (abstract_change_detector.js:58)
    at t.triggerEventHandlers (view.js:221)
    at eval (viewFactory_e:361)
    at dom_renderer.js:277
    at dom_events.js:28
    at e.run (angular2-polyfills.js:1243)
    at e.run (ng_zone.js:343)
    at t.run (ng_zone.js:292)
    at HTMLAnchorElement.i (dom_events.js:28)
```

Node version 5.6.0
NPM version 3.6.0

**Comment by ocombe** [comment]
Did you change anything to the actual code?
If you just did npm install, did it install angular2 beta 5 (that was just released)?

**Comment by Enlitened** [comment]
I didn't change anything in the code, just did a pull, npm install and a build.

I pulled it a couple days ago, it's got angular2 beta 3 installed.

**Comment by ocombe** [comment]
Ok thanks, I will fix this then :)

**Comment by ocombe** [comment]
It turns out that it's yet another problem with angular 2, it will be fixed in beta 6, until then I disabled "mangle" for UglifyJS

**Comment by deepakgduber9** [comment]
hi @ocombe Still i am facing this issue. I am using angular2 beta.8

**Comment by Foxandxss** [comment]
I think we should probably disable mangle entirely for a few weeks.

**Comment by deepakgd** [comment]
yes after mangle false its working fine. thanks @Foxandxss
