### ISSUE TITLE
Service workers

### ISSUE THREAD

**Issue by NathanWalker** [ocombe/ng2-webpack#3]
Just for thought...

What do you think about adding a service worker setup here? With a manifest and task in webpack?

**Comment by ocombe** [comment]
Ahh good idea, wanna try to do it? Or I can

**Comment by NathanWalker** [comment]
I may have time tomorrow, going to catch some zzzz's now, give it a shot!

We can explore and collab on some things on a branch if you push something.

Pretty good resources here to get going:
https://infowrap.com/372/notes/72276?token=3bef9fd586683fdc7908

**Comment by ocombe** [comment]
Thanks, I'll see if I can do it.
I added you as a collaborator as well.

**Comment by ocombe** [comment]
Actually I'll let you do it. There is a service-worker.js file in app/public that you can use

**Comment by ocombe** [comment]
There is https://github.com/robwormald/ng2-application-shell as a demo if needed. But I don't think that we should implement this here in the end, it would change the application too much and this wouldn't be a simple starter anymore.

**Comment by NathanWalker** [comment]
I have seen that demo and it looks interesting and also pretty incomplete. You're right, it would change this simple starter to be a bit more sophisticated. I'll close this and plan for a couple things down the line. Once the ng2-application-shell is a bit more complete, we can fork this seed to create another seed with this same setup but implementing service workers. :+1:

**Comment by ocombe** [comment]
yes :)
