### ISSUE TITLE
lodash?

### ISSUE THREAD

**Issue by NathanWalker** [ocombe/ng2-webpack#4]
I feel like lodash is an essential frontend library. I don't see many seeds using it out of the box and I think they should. It helps lessen a ton of boilerplate code and reduces lines of code in any production app.
What do you think we break the mold and be a starter that provides lodash integration out of the box?

**Comment by ocombe** [comment]
I don't know, I added it to my app based on the starter, but I'm not sure that we should add it there. It's easy to integrate if needed.

**Comment by NathanWalker** [comment]
Eh you're right. I get these ideas sometimes ya know and I'm glad there's another voice ;)

**Comment by ocombe** [comment]
That's the problem between a personal starter and a generic one. You always want to add the stuff that you personally always use, but then it gets in the way of what other people use...
We could have another branch for that though

**Comment by NathanWalker** [comment]
It sounds like angular2-webpack-starter is going that direction with
simplifying itself and then a new repo will be created with kind of the
ultimate sophisticated setup.

Yeah, we can explore another fork of this for that.

**Comment by ocombe** [comment]
yeah, we should probably move the integration of ng2-translate to that fork/other repo as well

**Comment by NathanWalker** [comment]
+1

You create it and I will contribute :)

**Comment by ocombe** [comment]
I cannot fork my own repo, but I added an "advanced" branch.
I'll update the doc later to explain that, gotta finish breakfast & go to work before.
