### ISSUE TITLE
If you import bootstrap, it flickers on initial load because bootstrap stylesheet isn't rendered before js

### ISSUE THREAD

**Issue by qdouble** [ocombe/ng2-webpack#5]
Can you change it so that when you do a build it renders the stylesheet on top of js instead of it being in one? Or is there another work around? Seems like having it together can cause flicker with using Bootstrap.

**Comment by ocombe** [comment]
You can include "global" css styles from the "app/style" folder, this will generate an external css file that is included in index.html (and thus is loaded like we're used to).
You just need to require it in one of your files (usually the app.ts, at the beginning, or the vendor.ts).
Let me know if that fixes the problem for you.

**Comment by qdouble** [comment]
Okay, requiring it in vendor.ts did the trick thanks.

**Comment by ocombe** [comment]
Perfect :)
:+1:

**Comment by hijoncon** [comment]
I experiencing the same issue.

I added this in vendor.ts
import 'bootstrap-sass/assets/stylesheets/_bootstrap.scss';

ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./~/raw-loader!./~/postcss-loader!./~/sass-loader!./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss
Module build failed: 
/*!
             ^
      Invalid CSS after "module.exports": expected "{", was '= "@charset \\"UTF-8'
      in /Users/x203949/Sites/angular2-webpack/node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss (line 1, column 15)
 @ ./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss 4:14-250
