### ISSUE TITLE
Beta 1 breaking on production build, but working in development.

### ISSUE THREAD

**Issue by qdouble** [ocombe/ng2-webpack#7]
Hey, I'm running into an issue since upgrading to beta 1 where it will run fine but give errors like this when doing a production build...

```
No provider for t! (t -> t)
```

I've also seen undefined errors after with another app copy...any ideas as to what may be causing this? It runs fine in beta 0 and fine in beta 1 on watch, but not build.

**Comment by ocombe** [comment]
You're right, I'll look into it, thanks a lot for the report

**Comment by ocombe** [comment]
It looks like there's a lot of error with minified builds in beta.1:
https://github.com/angular/angular/issues/6366
https://github.com/angular/angular/issues/6380

I disabled "mangle" for the uglify js plugin until they fix the beta :-/

**Comment by qdouble** [comment]
Hey, yes, I see most of the issues I'm experiencing are beta 1 issues, not just webpack issues. I even ran into this issue that goes beyond being minified where there's an error if try to set class attributes even without being minified: https://github.com/angular/angular/issues/6374

I guess I'll stick with beta 0 until some of the obvious bugs are patched. Thanks.

**Comment by ocombe** [comment]
It will be fixed once [this PR](https://github.com/angular/angular/pull/6397) has been merged

**Comment by ocombe** [comment]
This has been fixed with https://github.com/angular/angular/commit/eda4c3eb4c823029b885fdfcd602a8c3c93f0d31
We just need a new beta now.

**Comment by ocombe** [comment]
This has been fixed in beta.2 !
