### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by qdouble** [ocombe/ng2-webpack#9]
Hello, could you put me in the right direction of how to add and import tsd to this seed? Thanks.

**Comment by ocombe** [comment]
You can just import a typing in one of your ts files (like src/vendor.ts) like any other import of a ts file.
Or you can use the npm typings module, take a look at that: https://github.com/AngularClass/angular2-webpack-starter
there is a typings.json file, and the typings are generated by a post install script in package.json, then the main file of the typings is loaded in the tsconfig.json 'files' parameter

**Comment by qdouble** [comment]
Got it working with the first suggestion, thanks a million.

**Comment by ocombe** [comment]
:+1: perfect

**Comment by qdouble** [comment]
One issue still though, I see the compiler is throwing up an error 
```
ERROR in ./src/app/components/affiliates/manage.ts
(11,20): error TS2307: Cannot find module 'underscore'.
```
where I'm importing it like this:
```
import * as _ from 'underscore';
```

It's functioning, but I'm just wondering how to get rid of the compiler error

**Comment by ocombe** [comment]
I think that underscore, like lodash, doesn't export valid ES6 modules yet.
Change your import to `var _ = require('underscore');` and it should work.

**Comment by qdouble** [comment]
That works great, thanks again.

**Comment by born2net** [comment]
I am using system (not commonjs) so can't have any require statements in my code, any solution to:
```import * as _ from 'underscore';```

regards

Sean

**Comment by ollwenjones** [comment]
@born2net I was able to add `import 'lodash';` in my vendor.ts, and then 
`import * as _ from 'lodash';` in my service and it worked fine. Can't recall if underscore has the exportable memebers. Also have to make sure you install a typing for it.

**Comment by born2net** [comment]
tx yes used lodash as well... tx
